<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
require __DIR__ . '/fakes/TestPattern.php';
require __DIR__ . '/fakes/TestShape.php';
// @codeCoverageIgnoreEnd
