<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
require __DIR__ . '/canvas/Canvas.php';
require __DIR__ . '/canvas/CanvasIterator.php';
require __DIR__ . '/Color.php';
require __DIR__ . '/exceptions/Exception.php';
require __DIR__ . '/intersection/Intersection.php';
require __DIR__ . '/intersection/IntersectionCollection.php';
require __DIR__ . '/intersection/IntersectionCollectionIterator.php';
require __DIR__ . '/exceptions/IntersectionHasNoHitException.php';
require __DIR__ . '/exceptions/InvalidArgumentException.php';
require __DIR__ . '/math/Matrix.php';
require __DIR__ . '/objects/Object_.php';
require __DIR__ . '/exceptions/OutOfBoundsException.php';
require __DIR__ . '/math/Tuple.php';
require __DIR__ . '/math/Point.php';
require __DIR__ . '/canvas/PortablePixmapMapper.php';
require __DIR__ . '/Ray.php';
require __DIR__ . '/exceptions/RuntimeException.php';
require __DIR__ . '/objects/Sphere.php';
require __DIR__ . '/math/Vector.php';
require __DIR__ . '/canvas/WebpMapper.php';
// @codeCoverageIgnoreEnd
