<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
require __DIR__ . '/Color.php';
require __DIR__ . '/exceptions/Exception.php';
require __DIR__ . '/exceptions/RuntimeException.php';
require __DIR__ . '/Tuple.php';
// @codeCoverageIgnoreEnd
