<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'sebastianbergmann\\raytracer\\ansimapper' => '/canvas/AnsiMapper.php',
                'sebastianbergmann\\raytracer\\camera' => '/Camera.php',
                'sebastianbergmann\\raytracer\\canvas' => '/canvas/Canvas.php',
                'sebastianbergmann\\raytracer\\canvasiterator' => '/canvas/CanvasIterator.php',
                'sebastianbergmann\\raytracer\\checkerspattern' => '/material/CheckersPattern.php',
                'sebastianbergmann\\raytracer\\color' => '/Color.php',
                'sebastianbergmann\\raytracer\\exception' => '/exceptions/Exception.php',
                'sebastianbergmann\\raytracer\\gradientpattern' => '/material/GradientPattern.php',
                'sebastianbergmann\\raytracer\\intersection' => '/intersection/Intersection.php',
                'sebastianbergmann\\raytracer\\intersectioncollection' => '/intersection/IntersectionCollection.php',
                'sebastianbergmann\\raytracer\\intersectioncollectioniterator' => '/intersection/IntersectionCollectionIterator.php',
                'sebastianbergmann\\raytracer\\intersectionhasnohitexception' => '/exceptions/IntersectionHasNoHitException.php',
                'sebastianbergmann\\raytracer\\invalidargumentexception' => '/exceptions/InvalidArgumentException.php',
                'sebastianbergmann\\raytracer\\material' => '/material/Material.php',
                'sebastianbergmann\\raytracer\\matrix' => '/math/Matrix.php',
                'sebastianbergmann\\raytracer\\outofboundsexception' => '/exceptions/OutOfBoundsException.php',
                'sebastianbergmann\\raytracer\\pattern' => '/material/Pattern.php',
                'sebastianbergmann\\raytracer\\plane' => '/shapes/Plane.php',
                'sebastianbergmann\\raytracer\\pointlight' => '/PointLight.php',
                'sebastianbergmann\\raytracer\\portablepixmapmapper' => '/canvas/PortablePixmapMapper.php',
                'sebastianbergmann\\raytracer\\preparedcomputation' => '/intersection/PreparedComputation.php',
                'sebastianbergmann\\raytracer\\ray' => '/math/Ray.php',
                'sebastianbergmann\\raytracer\\ringpattern' => '/material/RingPattern.php',
                'sebastianbergmann\\raytracer\\runtimeexception' => '/exceptions/RuntimeException.php',
                'sebastianbergmann\\raytracer\\shape' => '/shapes/Shape.php',
                'sebastianbergmann\\raytracer\\shapecollection' => '/shapes/ShapeCollection.php',
                'sebastianbergmann\\raytracer\\shapecollectioniterator' => '/shapes/ShapeCollectionIterator.php',
                'sebastianbergmann\\raytracer\\sphere' => '/shapes/Sphere.php',
                'sebastianbergmann\\raytracer\\stripepattern' => '/material/StripePattern.php',
                'sebastianbergmann\\raytracer\\transformations' => '/math/Transformations.php',
                'sebastianbergmann\\raytracer\\tuple' => '/math/Tuple.php',
                'sebastianbergmann\\raytracer\\webpmapper' => '/canvas/WebpMapper.php',
                'sebastianbergmann\\raytracer\\world' => '/World.php',
                'sebastianbergmann\\raytracer\\worldhasnolightexception' => '/exceptions/WorldHasNoLightException.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
